"""Load the course's running-example data and fetch real Indian company statements.

Two kinds of data live here:

1. **Course data (offline).** The fictional running examples, Kaveri Pumps & Motors Ltd and
   Nirmal Finance Ltd, are generated by ``tools/running_example/generate.py`` into
   ``tools/data/*.csv``. ``load_kaveri`` and ``load_nirmal`` read those CSVs into DataFrames whose
   **index is the line item** and whose **columns are periods** (``FY21`` ... ``FY26``). Amounts are
   in ₹ crore. Line-item keys are the generator's keys (``rev``, ``mat``, ``ebitda``, ``receivables``,
   ``cfo`` ...); see ``KAVERI_LINE_ITEMS`` for a plain-English description of each one.

2. **Real company data (network).** ``fetch_statements`` pulls income statement, balance sheet
   and cash-flow statement for an NSE/BSE ticker (``"ASIANPAINT.NS"``, ``"500820.BO"``) through
   OpenBB 4.x (``obb.equity.fundamental.income/balance/cash`` with ``provider="yfinance"``) when
   OpenBB is installed, falling back to raw ``yfinance``. ``fetch_price_info`` returns price, market
   cap, share count, beta and the analyst-target fields from ``yf.Ticker(t).info``.

Network caveats (read these before blaming the code):

* **VPNs frequently block Yahoo Finance** (requests to ``fc.yahoo.com`` / ``query2.finance.yahoo.com``
  fail or return empty frames). Disable the VPN before running any yfinance/OpenBB script.
* Yahoo gives at most ~4-5 annual and ~5 quarterly periods. For Indian companies quarterly
  coverage is patchy: quarters can be missing, and the quarterly balance sheet and cash-flow
  statement are often absent for some or all quarters (e.g. in Sep-2026 Asian Paints had no
  quarterly cash flow and only March/September balance sheets on Yahoo). The mandatory balance
  sheet for Indian listed companies is the half-yearly statement of assets and liabilities
  (SEBI LODR Reg. 33 - verify the current text at sebi.gov.in); some companies publish more.
* Vendor data are standardised by Yahoo, not by the company: always tie key lines back to the annual
  report (Module 10.2).
* Amounts from Yahoo are in **rupees**, not crore. Pass ``in_crore=True`` to divide by 1e7.
* Scripts that print ``₹`` on Windows must wrap stdout first::

      import io, sys
      sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
"""
from __future__ import annotations

import importlib.util
import io
import re
import sys
import warnings
from pathlib import Path
from types import ModuleType
from typing import Any

import pandas as pd

__all__ = [
    "TOOLS_DIR",
    "DATA_DIR",
    "KAVERI_LINE_ITEMS",
    "load_kaveri",
    "load_nirmal",
    "kaveri_opening_balance",
    "kaveri_market_data",
    "fetch_statements",
    "fetch_price_info",
    "standardise_statement",
    "revenue_row",
    "to_snake_case",
]

TOOLS_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = TOOLS_DIR / "data"
RUNNING_EXAMPLE_DIR = TOOLS_DIR / "running_example"

_KAVERI_FILES = {
    "annual": "kaveri_pumps_annual.csv",
    "ratios": "kaveri_pumps_ratios.csv",
    "quarterly": "kaveri_pumps_quarterly.csv",
}
_NIRMAL_FILE = "nirmal_finance_annual.csv"

#: Plain-English meaning of every line item in the Kaveri annual frame (₹ crore).
KAVERI_LINE_ITEMS: dict[str, str] = {
    "rev": "Revenue from operations",
    "mat": "Cost of materials consumed incl. change in inventories (the 'COGS' proxy)",
    "emp": "Employee benefits expense (includes sbc)",
    "sbc": "Share-based payment expense (non-cash; inside emp)",
    "oth": "Other expenses",
    "ebitda": "EBITDA excluding other income = rev - mat - emp - oth",
    "dep_ppe": "Depreciation on PP&E",
    "rou_amort": "Amortisation of right-of-use (lease) assets",
    "int_amort": "Amortisation of intangibles",
    "da": "Total depreciation & amortisation",
    "ebit": "EBIT excluding other income = ebitda - da",
    "other_income": "Other income (entirely treasury income on cash + liquid funds)",
    "debt_int": "Finance cost on borrowings",
    "lease_int": "Finance cost on lease liabilities",
    "fin_cost": "Total finance costs = debt_int + lease_int",
    "exceptional": "Exceptional items, gain (+) / loss (-)",
    "pbt": "Profit before tax",
    "current_tax": "Current tax (= tax paid in the cash-flow statement)",
    "deferred_tax": "Deferred tax charge (= change in DTL)",
    "tax": "Total tax expense",
    "pat": "Profit after tax",
    "gross_block": "Gross block of PP&E incl. land",
    "acc_dep": "Accumulated depreciation",
    "net_block": "Net block = gross_block - acc_dep",
    "cwip": "Capital work-in-progress",
    "rou": "Right-of-use assets",
    "intangibles": "Intangible assets (net)",
    "inventory": "Inventories",
    "receivables": "Trade receivables",
    "oca": "Other current assets",
    "cash": "Cash & cash equivalents",
    "cur_inv": "Current investments (liquid mutual funds)",
    "total_assets": "Total assets",
    "share_capital": "Equity share capital (6.0 Cr shares x ₹5)",
    "other_equity": "Other equity (reserves & surplus)",
    "equity": "Total equity = share_capital + other_equity",
    "lt_debt": "Non-current borrowings (term loans)",
    "st_debt": "Current borrowings (working-capital loans + current maturities)",
    "lease_liab": "Lease liabilities",
    "payables": "Trade payables",
    "ocl": "Other current liabilities & provisions",
    "dtl": "Deferred tax liability (net)",
    "total_le": "Total equity & liabilities",
    "op_before_wc": "Operating profit before working-capital changes",
    "d_inv": "Increase in inventories (a cash outflow when positive)",
    "d_rec": "Increase in receivables (outflow when positive)",
    "d_oca": "Increase in other current assets (outflow when positive)",
    "d_pay": "Increase in payables (inflow when positive)",
    "d_ocl": "Increase in other current liabilities (inflow when positive)",
    "wc_change": "Net working-capital cash effect (negative = cash absorbed)",
    "cfo": "Cash flow from operations",
    "capex_ppe": "Purchase of PP&E incl. CWIP",
    "capex_int": "Purchase of intangibles",
    "d_cur_inv": "Net purchase (+) / sale (-) of current investments",
    "asset_sale": "Proceeds from sale of land",
    "cfi": "Cash flow from investing",
    "d_lt": "Net term-loan drawdown (+) / repayment (-)",
    "d_st": "Net working-capital loan drawdown (+) / repayment (-)",
    "lease_payment": "Lease payments (principal + interest)",
    "dividends": "Dividends paid in the year",
    "cff": "Cash flow from financing",
    "net_cash": "Net change in cash",
}

_MODULE_CACHE: dict[str, ModuleType] = {}


# ---------------------------------------------------------------------------
# Running-example helpers
# ---------------------------------------------------------------------------
def _load_running_example(name: str) -> ModuleType:
    """Import ``tools/running_example/<name>.py`` as a module (cached).

    The generator scripts re-wrap ``sys.stdout`` at import time (so they can print ₹ on Windows).
    Doing that inside a library call would detach/close the caller's stdout (pytest capture,
    Jupyter), so the import runs with a throw-away stdout that is restored afterwards.
    ``main()`` is never called, so no files are rewritten.
    """
    if name in _MODULE_CACHE:
        return _MODULE_CACHE[name]
    path = RUNNING_EXAMPLE_DIR / f"{name}.py"
    if not path.exists():
        raise FileNotFoundError(f"running-example module not found: {path}")
    spec = importlib.util.spec_from_file_location(f"_fi_running_example_{name}", path)
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        raise ImportError(f"cannot import {path}")
    module = importlib.util.module_from_spec(spec)
    saved_stdout = sys.stdout
    sys.stdout = io.TextIOWrapper(io.BytesIO(), encoding="utf-8")
    try:
        spec.loader.exec_module(module)
    finally:
        sys.stdout = saved_stdout
    _MODULE_CACHE[name] = module
    return module


def _read_frame(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path, index_col="line_item")
    df.index.name = "line_item"
    df.columns.name = "period"
    return df.apply(pd.to_numeric, errors="coerce").astype(float)


def kaveri_opening_balance() -> pd.Series:
    """Kaveri's opening balance sheet at 31-Mar-2020 ("FY20"), ₹ crore.

    Needed because FY21 ratios on *average* balances (ROE, ROCE, ROIC) use the FY20 closing
    balance sheet, which is not a column of the annual CSV. Values come straight from the
    generator's ``OPEN`` dict, plus derived ``net_block``, ``equity`` and ``total_assets``.
    """
    gen = _load_running_example("generate")
    o = dict(gen.OPEN)
    o["net_block"] = round(o["gross_block"] - o["acc_dep"], 1)
    o["equity"] = round(o["share_capital"] + o["other_equity"], 1)
    o["total_assets"] = round(
        o["net_block"] + o["cwip"] + o["rou"] + o["intangibles"] + o["inventory"] + o["receivables"]
        + o["oca"] + o["cash"] + o["cur_inv"], 1)
    o["total_le"] = round(
        o["equity"] + o["lt_debt"] + o["st_debt"] + o["lease_liab"] + o["payables"] + o["ocl"] + o["dtl"], 1)
    return pd.Series(o, name="FY20", dtype=float)


def kaveri_market_data() -> pd.DataFrame:
    """Kaveri per-year market data (fictional): share price at 31-March, DPS paid, share counts.

    Rows: ``price`` (₹), ``dps_paid`` (₹, dividend per share paid during the year),
    ``shares`` (crore, basic), ``diluted_shares`` (crore). Columns FY21..FY26.
    """
    gen = _load_running_example("generate")
    k = gen.K
    years = list(gen.YEARS)
    return pd.DataFrame(
        {
            "price": [float(p) for p in k["price_mar"]],
            "dps_paid": [float(d) for d in k["dps_paid"]],
            "shares": [float(k["shares"])] * len(years),
            "diluted_shares": [float(s) for s in k["diluted_shares"]],
        },
        index=years,
    ).T


def load_kaveri(kind: str = "annual") -> pd.DataFrame:
    """Load Kaveri Pumps & Motors Ltd (fictional) data as a line-item x period DataFrame.

    Parameters
    ----------
    kind : {"annual", "ratios", "quarterly"}
        ``"annual"`` - the full P&L, balance sheet and cash-flow statement, FY21-FY26 (₹ crore);
        ``"ratios"`` - the generator's ratio table (decimals, e.g. 0.138 = 13.8%);
        ``"quarterly"`` - Q1 FY26 ... Q1 FY27.

    The annual frame carries metadata in ``df.attrs`` so that ``fi.ratios.ratio_dashboard`` can
    reproduce the course ratio table without extra arguments:

    * ``opening`` (dict) and ``opening_for`` (``"FY21"``): the 31-Mar-2020 balance sheet;
    * ``price``, ``dps_paid``, ``diluted_shares`` (dict by FY), ``shares`` (6.0 crore),
      ``tax_rate`` (0.2517), ``cmp`` (₹390 on 18-Sep-2026), ``units`` ("₹ crore").

    Example
    -------
    >>> df = load_kaveri()
    >>> float(df.at["rev", "FY26"])
    1318.0
    """
    kind = kind.lower()
    if kind not in _KAVERI_FILES:
        raise ValueError(f"kind must be one of {sorted(_KAVERI_FILES)}, got {kind!r}")
    df = _read_frame(DATA_DIR / _KAVERI_FILES[kind])
    gen = _load_running_example("generate")
    df.attrs["company"] = "Kaveri Pumps & Motors Ltd (fictional)"
    df.attrs["units"] = "₹ crore"
    df.attrs["kind"] = kind
    if kind == "annual":
        mkt = kaveri_market_data()
        df.attrs["opening"] = kaveri_opening_balance().to_dict()
        df.attrs["opening_for"] = gen.YEARS[0]
        df.attrs["price"] = mkt.loc["price"].to_dict()
        df.attrs["dps_paid"] = mkt.loc["dps_paid"].to_dict()
        df.attrs["diluted_shares"] = mkt.loc["diluted_shares"].to_dict()
        df.attrs["shares"] = float(gen.K["shares"])
        df.attrs["face_value"] = 5.0
        df.attrs["tax_rate"] = float(gen.K["tax_rate"])
        df.attrs["cmp"] = float(gen.K["cmp"])
    return df


def load_nirmal() -> pd.DataFrame:
    """Load Nirmal Finance Ltd (fictional NBFC) FY21-FY26 as a line-item x period DataFrame.

    Includes P&L, balance sheet, asset-quality and ratio rows exactly as produced by the
    generator (ratios as decimals). ``df.attrs["opening"]`` holds the 31-Mar-2020 opening
    balances (gross loans, ECL, liquid assets, borrowings, equity).
    """
    df = _read_frame(DATA_DIR / _NIRMAL_FILE)
    gen = _load_running_example("generate")
    df.attrs["company"] = "Nirmal Finance Ltd (fictional)"
    df.attrs["units"] = "₹ crore"
    df.attrs["opening"] = dict(gen.N_OPEN)
    df.attrs["opening_for"] = gen.YEARS[0]
    df.attrs["tax_rate"] = float(gen.N["tax_rate"])
    return df


# ---------------------------------------------------------------------------
# Real-company data (network)
# ---------------------------------------------------------------------------
def to_snake_case(name: str) -> str:
    """Convert Yahoo's CamelCase line items (``"TotalRevenue"``) to OpenBB-style snake_case.

    Mirrors ``openbb_core.provider.utils.helpers.to_snake_case`` so that the OpenBB and raw
    yfinance routes produce the same row names (``"total_revenue"``, ``"basic_eps"``).
    """
    s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", str(name))
    return re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1).lower().replace(" ", "_").replace("__", "_")


def _normalise_period(period: str) -> str:
    p = period.lower().strip()
    if p in {"annual", "a", "year", "yearly", "fy"}:
        return "annual"
    if p in {"quarter", "quarterly", "q"}:  # OpenBB wants "quarter", not "quarterly"
        return "quarter"
    raise ValueError(f"period must be 'annual' or 'quarter', got {period!r}")


#: Canonical rows added by ``standardise_statement``: first candidate present wins (per period).
CANONICAL_ROWS: dict[str, dict[str, list[str]]] = {
    "income": {
        # Yahoo/OpenBB report either or both; 'total_revenue' preferred, else 'operating_revenue'.
        "revenue": ["total_revenue", "operating_revenue", "revenue"],
        "cogs": ["cost_of_revenue", "reconciled_cost_of_revenue"],
        "ebitda": ["ebitda", "normalized_ebitda"],
        "ebit": ["ebit", "operating_income"],
        "interest_expense": ["interest_expense", "interest_expense_non_operating"],
        "pretax_income": ["pretax_income", "total_pre_tax_income"],
        "tax": ["tax_provision"],
        "net_income": ["net_income_common_stockholders", "net_income_attributable_to_common_shareholders",
                       "net_income"],
        "depreciation": ["reconciled_depreciation", "depreciation_and_amortization_in_income_statement"],
        "eps_basic": ["basic_eps", "basic_earnings_per_share"],
        "eps_diluted": ["diluted_eps", "diluted_earnings_per_share"],
    },
    "balance": {
        "total_assets": ["total_assets"],
        "current_assets": ["current_assets", "total_current_assets"],
        "current_liabilities": ["current_liabilities", "total_current_liabilities"],
        "cash": ["cash_and_cash_equivalents"],
        "cash_and_st_investments": ["cash_cash_equivalents_and_short_term_investments"],
        "receivables": ["accounts_receivable", "receivables"],
        "inventory": ["inventory", "inventories"],
        "payables": ["accounts_payable", "payables"],
        "net_ppe": ["net_ppe", "plant_property_equipment_net"],
        "total_debt": ["total_debt"],
        "total_equity": ["common_stock_equity", "stockholders_equity", "total_common_equity"],
        "retained_earnings": ["retained_earnings"],
        "total_liabilities": ["total_liabilities_net_minority_interest"],
        "shares": ["ordinary_shares_number", "share_issued"],
    },
    "cash": {
        "cfo": ["operating_cash_flow", "cash_flow_from_continuing_operating_activities"],
        "capex": ["capital_expenditure"],
        "fcf": ["free_cash_flow"],
        "dividends_paid": ["cash_dividends_paid", "common_stock_dividend_paid"],
        "d_and_a": ["depreciation_and_amortization", "depreciation_amortization_depletion"],
    },
}

_NO_SCALE_PATTERNS = ("eps", "per_share", "shares", "share_issued", "rate", "ratio")


def standardise_statement(df: pd.DataFrame, statement: str, in_crore: bool = False) -> pd.DataFrame:
    """Normalise a raw statement to the course layout and add canonical rows.

    Layout: index = snake_case line item, columns = period-end dates ``"YYYY-MM-DD"`` sorted
    oldest -> newest (same orientation as ``load_kaveri``). Canonical rows (``revenue``,
    ``net_income``, ``cfo``, ``capex`` ...; see ``CANONICAL_ROWS``) are added when missing, taking
    the first available candidate per period - this is where the ``total_revenue`` vs
    ``operating_revenue`` difference is handled.

    ``in_crore=True`` divides monetary rows by 1e7 (per-share, share-count and rate rows untouched).
    """
    if df is None or df.empty:
        return pd.DataFrame()
    out = df.copy()
    out.index = [to_snake_case(i) for i in out.index]
    out = out[~out.index.duplicated(keep="first")]
    cols = []
    for c in out.columns:
        try:
            cols.append(pd.Timestamp(c).strftime("%Y-%m-%d"))
        except (ValueError, TypeError):
            cols.append(str(c))
    out.columns = cols
    out = out.apply(pd.to_numeric, errors="coerce")
    out = out.reindex(sorted(out.columns), axis=1)
    for canon, candidates in CANONICAL_ROWS.get(statement, {}).items():
        if canon in out.index:
            continue
        present = [c for c in candidates if c in out.index]
        if not present:
            continue
        row = out.loc[present[0]].copy()
        for c in present[1:]:
            row = row.fillna(out.loc[c])
        out.loc[canon] = row
    if in_crore:
        scale = [not any(p in idx for p in _NO_SCALE_PATTERNS) for idx in out.index]
        out.loc[scale] = out.loc[scale] / 1e7
    out.index.name = "line_item"
    out.columns.name = "period"
    return out


def revenue_row(income: pd.DataFrame) -> pd.Series:
    """Return revenue from a statement frame, whichever of ``total_revenue``/``operating_revenue`` exists."""
    for key in ("revenue", "total_revenue", "operating_revenue"):
        if key in income.index:
            return income.loc[key]
    raise KeyError("no revenue row (looked for revenue / total_revenue / operating_revenue)")


def _fetch_openbb(statement: str, ticker: str, period: str, provider: str, limit: int | None) -> pd.DataFrame:
    from openbb import obb  # imported lazily: slow, and optional

    fn = {
        "income": obb.equity.fundamental.income,
        "balance": obb.equity.fundamental.balance,
        "cash": obb.equity.fundamental.cash,
    }[statement]
    kwargs: dict[str, Any] = {"symbol": ticker, "provider": provider, "period": period}
    if limit is not None:
        kwargs["limit"] = limit
    res = fn(**kwargs)
    rows = [r.model_dump() if hasattr(r, "model_dump") else dict(r) for r in (res.results or [])]
    if not rows:
        return pd.DataFrame()
    wide = pd.DataFrame(rows)
    if "period_ending" not in wide.columns:
        raise ValueError("OpenBB result has no 'period_ending' column")
    wide = wide.set_index("period_ending").drop(columns=["fiscal_period", "fiscal_year"], errors="ignore")
    return wide.T


def _fetch_yfinance(statement: str, ticker: str, period: str, limit: int | None) -> pd.DataFrame:
    import yfinance as yf

    t = yf.Ticker(ticker)
    getter = {"income": t.get_income_stmt, "balance": t.get_balance_sheet, "cash": t.get_cash_flow}[statement]
    raw = getter(as_dict=False, pretty=False, freq="yearly" if period == "annual" else "quarterly")
    if raw is None or raw.empty:
        return pd.DataFrame()
    if limit is not None:
        raw = raw.iloc[:, :limit]  # Yahoo returns newest first
    return raw


def fetch_statements(
    ticker: str,
    period: str = "annual",
    provider: str = "yfinance",
    *,
    limit: int | None = 5,
    use_openbb: bool | None = None,
    in_crore: bool = False,
) -> dict[str, pd.DataFrame]:
    """Fetch income statement, balance sheet and cash-flow statement for a listed company.

    Parameters
    ----------
    ticker : str
        Yahoo symbol, e.g. ``"ASIANPAINT.NS"`` (NSE) or ``"500820.BO"`` (BSE).
    period : {"annual", "quarter"}
        ``"quarterly"`` is accepted and mapped to ``"quarter"`` (the value OpenBB expects).
    provider : str
        OpenBB provider (default ``"yfinance"``, which needs no API key). The FMP free tier does
        **not** cover Indian listings.
    limit : int or None
        Number of periods (the OpenBB yfinance provider caps this at 5).
    use_openbb : bool or None
        ``None`` (default) uses OpenBB if importable, else yfinance; ``True`` forces OpenBB (errors
        propagate as warnings and the yfinance fallback is still tried); ``False`` skips OpenBB.
    in_crore : bool
        Divide monetary rows by 1e7 (Yahoo reports rupees).

    Returns
    -------
    dict with keys ``"income"``, ``"balance"``, ``"cash"``; each a DataFrame (line item x period-end
    date, oldest -> newest) with canonical rows added (``revenue``, ``net_income``, ``cfo``...).
    A statement that cannot be fetched comes back as an empty DataFrame with a warning.

    Notes
    -----
    Needs network access. **Disable any VPN** - Yahoo Finance endpoints are commonly blocked.
    OpenBB route: ``obb.equity.fundamental.income(symbol=..., provider="yfinance", period="annual")``.
    """
    period = _normalise_period(period)
    if use_openbb is None:
        use_openbb = importlib.util.find_spec("openbb") is not None
    out: dict[str, pd.DataFrame] = {}
    for statement in ("income", "balance", "cash"):
        raw = pd.DataFrame()
        source = None
        if use_openbb:
            try:
                raw = _fetch_openbb(statement, ticker, period, provider, limit)
                source = "openbb"
            except Exception as exc:  # noqa: BLE001 - network/provider errors vary widely
                warnings.warn(f"OpenBB {statement} fetch failed for {ticker} ({exc!r}); trying yfinance",
                              stacklevel=2)
        if raw is None or raw.empty:
            try:
                raw = _fetch_yfinance(statement, ticker, period, limit)
                source = "yfinance"
            except Exception as exc:  # noqa: BLE001
                warnings.warn(f"yfinance {statement} fetch failed for {ticker} ({exc!r}). "
                              "Is a VPN blocking Yahoo Finance?", stacklevel=2)
                raw = pd.DataFrame()
        std = standardise_statement(raw, statement, in_crore=in_crore)
        if std.empty:
            warnings.warn(f"{statement} statement for {ticker} ({period}) is empty", stacklevel=2)
        std.attrs.update(ticker=ticker, period=period, source=source,
                         units="₹ crore" if in_crore else "reporting currency (₹ for Indian listings)")
        out[statement] = std
    return out


_INFO_FIELDS = {
    "name": "longName",
    "currency": "currency",
    "financial_currency": "financialCurrency",
    "price": ("currentPrice", "regularMarketPrice"),
    "market_cap": "marketCap",
    "enterprise_value": "enterpriseValue",
    "shares_outstanding": "sharesOutstanding",
    "beta": "beta",
    "trailing_pe": "trailingPE",
    "forward_pe": "forwardPE",
    "price_to_book": "priceToBook",
    "book_value_per_share": "bookValue",
    "trailing_eps": "trailingEps",
    "dividend_yield": "dividendYield",
    "fifty_two_week_high": "fiftyTwoWeekHigh",
    "fifty_two_week_low": "fiftyTwoWeekLow",
    "target_mean": "targetMeanPrice",
    "target_median": "targetMedianPrice",
    "target_high": "targetHighPrice",
    "target_low": "targetLowPrice",
    "n_analysts": "numberOfAnalystOpinions",
    "recommendation": "recommendationKey",
    "sector": "sector",
    "industry": "industry",
}


def fetch_price_info(ticker: str) -> dict[str, Any]:
    """Price, market cap, shares, beta and analyst-target fields from ``yf.Ticker(ticker).info``.

    Returns a flat dict with keys: ``ticker, name, currency, financial_currency, price, market_cap,
    enterprise_value, shares_outstanding, beta, trailing_pe, forward_pe, price_to_book,
    book_value_per_share, trailing_eps, dividend_yield, fifty_two_week_high, fifty_two_week_low,
    target_mean, target_median, target_high, target_low, n_analysts, recommendation, sector,
    industry``. Missing fields are ``None``. Values are passed through as Yahoo reports them
    (market cap in rupees; ``dividend_yield`` is in *percent* in recent yfinance versions).

    Yahoo's beta is a 5-year monthly regression against a US-centric default and is often
    meaningless for Indian stocks - estimate your own (Module 06.2). Analyst targets are consensus
    snapshots, not facts. Needs network; disable VPNs.
    """
    import yfinance as yf

    info = yf.Ticker(ticker).info or {}
    out: dict[str, Any] = {"ticker": ticker}
    for key, src in _INFO_FIELDS.items():
        if isinstance(src, tuple):
            out[key] = next((info.get(s) for s in src if info.get(s) is not None), None)
        else:
            out[key] = info.get(src)
    return out
