"""Build docs/appendix/glossary.md and the Anki deck in flashcards/ from every lesson's "Key terms" table.

    python tools/build_glossary.py

Re-run after editing any lesson's Key terms. The glossary is generated — edit the lessons, not the output.
"""
from __future__ import annotations

import csv
import io
import re
import sys
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
OUT_MD = DOCS / "appendix" / "glossary.md"
OUT_DIR = ROOT / "flashcards"

SKIP = {"exercises.md", "solutions.md", "index.md"}


def lesson_code(rel: str) -> str:
    """'02-accounting/01-x.md' -> '02.1'; case studies -> 'I1' / 'G1'; mocks -> 'M14.1'."""
    parts = rel.split("/")
    mod = parts[0][:2]
    if parts[0].startswith("13-case-studies") and len(parts) == 3:
        prefix = "I" if parts[1] == "india" else "G"
        return f"{prefix}{int(parts[2][:2])}"
    num = re.match(r"(\d+)", parts[-1])
    return f"{mod}.{int(num.group(1))}" if num else mod


def harvest():
    terms: dict[str, dict] = {}
    for md in sorted(DOCS.rglob("*.md")):
        rel = md.relative_to(DOCS).as_posix()
        if rel.startswith("appendix/") or md.name in SKIP or "/answer-keys/" in rel or md.name.startswith("."):
            continue
        text = md.read_text(encoding="utf-8")
        m = re.search(r"^##\s+Key terms\s*$(.*?)(?=^##\s|\Z)", text, flags=re.M | re.S)
        if not m:
            continue
        for line in m.group(1).splitlines():
            if not line.strip().startswith("|"):
                continue
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if len(cells) < 2 or set(cells[0]) <= set(":- ") or cells[0].lower().strip("*") in ("term", "concept"):
                continue
            term = re.sub(r"\*\*|`", "", cells[0]).strip()
            meaning = cells[1].strip()
            if not term or not meaning:
                continue
            key = re.sub(r"[^a-z0-9]", "", term.lower()).rstrip("s") or term.lower()
            e = terms.setdefault(key, {"term": term, "meanings": [], "lessons": []})
            if meaning not in e["meanings"]:
                e["meanings"].append(meaning)
            if rel not in e["lessons"]:
                e["lessons"].append(rel)
    return sorted(terms.values(), key=lambda e: re.sub(r"[^a-z0-9]", "", e["term"].lower()) or e["term"])


def first_letter(term: str) -> str:
    c = re.sub(r"^[^A-Za-z0-9]+", "", term)[:1].upper()
    return c if c.isalpha() else "0–9"


def main():
    items = harvest()
    groups: dict[str, list] = {}
    for e in items:
        groups.setdefault(first_letter(e["term"]), []).append(e)
    order = sorted(groups, key=lambda k: (k != "0–9", k))

    lines = [
        "# Glossary",
        "",
        f"**{len(items)} terms** from the Key-terms tables of every lesson and case study, A–Z. Each entry gives a",
        "plain-English definition and the lessons where the term is taught (click the code). Where two lessons",
        "define a term from different angles, both definitions are shown.",
        "",
        "The glossary is generated by `tools/build_glossary.py`, which also writes the Anki deck in",
        "[`flashcards/`](https://github.com/Sovi11/fundamental-investing-course/tree/main/flashcards). To change an",
        "entry, edit the lesson's Key terms and re-run the script. Formulas are collected on the",
        "[formula sheet](formula-sheet.md); Indian conventions (lakh, crore, FY) are in",
        "[Indian numbering & conventions](indian-numbering-and-conventions.md).",
        "",
        "**Jump to:** " + " · ".join(f"[{k}](#{'0-9' if k == '0–9' else k.lower()})" for k in order),
        "",
    ]
    for k in order:
        anchor = "0-9" if k == "0–9" else k.lower()
        lines += [f"## {k} {{#{anchor}}}", "", "| Term | Meaning | Taught in |", "|:--|:--|:--|"]
        for e in groups[k]:
            meaning = e["meanings"][0]
            if len(e["meanings"]) > 1:
                meaning += " · *Also:* " + e["meanings"][1]
            links = ", ".join(f"[{lesson_code(r)}](../{r})" for r in e["lessons"][:4])
            lines.append(f"| **{e['term']}** | {meaning} | {links} |")
        lines.append("")
    OUT_MD.write_text("\n".join(lines), encoding="utf-8", newline="\n")

    OUT_DIR.mkdir(exist_ok=True)
    plain = lambda s: re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", re.sub(r"\*\*|\*|`", "", s))
    with open(OUT_DIR / "fundamental-investing-glossary.tsv", "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f, delimiter="\t", lineterminator="\n")
        w.writerow(["#separator:tab"])
        w.writerow(["#html:false"])
        w.writerow(["#tags column:3"])
        for e in items:
            tags = " ".join(sorted({"fi::" + lesson_code(r).replace(".", "_") for r in e["lessons"]}))
            back = plain(" / ".join(e["meanings"][:2]))
            w.writerow([plain(e["term"]), back, tags])
    try:  # optional: a ready-to-import .apkg if genanki is installed (pip install genanki)
        import genanki

        model = genanki.Model(
            1607392319, "Fundamental Investing — term",
            fields=[{"name": "Term"}, {"name": "Meaning"}, {"name": "Lessons"}],
            templates=[{"name": "Term → meaning",
                        "qfmt": "<div style='font-size:22px'>{{Term}}</div>",
                        "afmt": "{{FrontSide}}<hr id=answer>{{Meaning}}<br><br><small>{{Lessons}}</small>"}])
        deck = genanki.Deck(2059400110, "Fundamental Investing — Glossary")
        for e in items:
            deck.add_note(genanki.Note(
                model=model,
                fields=[plain(e["term"]), plain(" / ".join(e["meanings"][:2])),
                        ", ".join(lesson_code(r) for r in e["lessons"])],
                guid=genanki.guid_for(e["term"].lower()),
                tags=sorted({"fi::" + lesson_code(r).replace(".", "_") for r in e["lessons"]})))
        genanki.Package(deck).write_to_file(str(OUT_DIR / "fundamental-investing-glossary.apkg"))
        apkg = " + .apkg"
    except ImportError:
        apkg = " (install genanki for an .apkg)"
    print(f"{len(items)} terms -> {OUT_MD.relative_to(ROOT)} and flashcards/ (.tsv{apkg})")


if __name__ == "__main__":
    main()
